### ISSUE TITLE
ModuleNotFoundError: No module named 'models'

### ISSUE THREAD

**Issue by bestK** [sml2h3/ddddocr-fastapi#37]
## 操作步骤
``` shell
git clone https://github.com/your-repo/ddddocr-api.git
cd ddddocr-api
docker build -t ddddocr-api .
docker run -d -p 8000:8000 --name ddddocr-api-container ddddocr-api
```
## 错误日志
```

[root@ci ddddocr-fastapi]# docker logs ddddocr-api-container
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 425, in main
    run(app, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 447, in run
    server.run()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 76, in serve
    config.load()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/config.py", line 448, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/app/./app/main.py", line 5, in <module>
    from models import OCRRequest, SlideMatchRequest, DetectionRequest, APIResponse
ModuleNotFoundError: No module named 'models'

```

**Comment by bestK** [comment]
```
- from models import OCRRequest, SlideMatchRequest, DetectionRequest, APIResponse
- from services import ocr_service


+ from app.models import OCRRequest, SlideMatchRequest, DetectionRequest, APIResponse
+ from app.services import ocr_service
```

**Comment by micookie** [comment]
问题还是存在：
![image](https://github.com/user-attachments/assets/d57b9fc1-9c4c-478a-89d2-92bb2bea18d6)
