### ISSUE TITLE
容器启动失败!

### ISSUE THREAD

**Issue by maxbad** [sml2h3/ddddocr-fastapi#38]
```
 2024-08-12 18:51:31 Traceback (most recent call last):
2024-08-12 18:51:31   File "/usr/local/bin/uvicorn", line 8, in <module>
2024-08-12 18:51:31     sys.exit(main())
2024-08-12 18:51:31   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
2024-08-12 18:51:31     return self.main(*args, **kwargs)
2024-08-12 18:51:31   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
2024-08-12 18:51:31     rv = self.invoke(ctx)
2024-08-12 18:51:31   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
2024-08-12 18:51:31     return ctx.invoke(self.callback, **ctx.params)
2024-08-12 18:51:31   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
2024-08-12 18:51:31     return __callback(*args, **kwargs)
2024-08-12 18:51:31   File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 425, in main
2024-08-12 18:51:31     run(app, **kwargs)
2024-08-12 18:51:31   File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 447, in run
2024-08-12 18:51:31     server.run()
2024-08-12 18:51:31   File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 68, in run
2024-08-12 18:51:31     return asyncio.run(self.serve(sockets=sockets))
2024-08-12 18:51:31   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
2024-08-12 18:51:31     return loop.run_until_complete(main)
2024-08-12 18:51:31   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
2024-08-12 18:51:31     return future.result()
2024-08-12 18:51:31   File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 76, in serve
2024-08-12 18:51:31     config.load()
2024-08-12 18:51:31   File "/usr/local/lib/python3.9/site-packages/uvicorn/config.py", line 448, in load
2024-08-12 18:51:31     self.loaded_app = import_from_string(self.app)
2024-08-12 18:51:31   File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line 24, in import_from_string
2024-08-12 18:51:31     raise exc from None
2024-08-12 18:51:31   File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
2024-08-12 18:51:31     module = importlib.import_module(module_str)
2024-08-12 18:51:31   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
2024-08-12 18:51:31     return _bootstrap._gcd_import(name[level:], package, level)
2024-08-12 18:51:31   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2024-08-12 18:51:31   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2024-08-12 18:51:31   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
2024-08-12 18:51:31   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2024-08-12 18:51:31   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
2024-08-12 18:51:31   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2024-08-12 18:51:31   File "/app/./app/main.py", line 5, in <module>
2024-08-12 18:51:31     from models import OCRRequest, SlideMatchRequest, DetectionRequest, APIResponse
2024-08-12 18:51:31 ModuleNotFoundError: No module named 'models'

 ```

**Comment by wyourname** [comment]
将from models import OCRReq...改为
from app.models import OCRReq....
from services import ocr_service 改为
from app.services import ocr_service
重新编译镜像即可

**Comment by maxbad** [comment]
> 将from models import OCRReq...改为 from app.models import OCRReq.... from services import ocr_service 改为 from app.services import ocr_service 重新编译镜像即可

ok, 可以了,谢谢哒
